version: "3"

services:
  hasherapi:
    build:
      context: ../
      dockerfile: build/hasherapi/Dockerfile
    ports:
      - "8088:8088"

  hasher:
    build:
      context: ../
      dockerfile: build/hasher/Dockerfile
    ports:
      - "8090:8090"
