version: "3"

services:
  hasherapi:
    container_name: hasherapi
    build:
      context: ../
      dockerfile: build/hasherapi/Dockerfile
    environment:
      - HASHERAPI_CONSUL_HOST=consul:8500
      - HASHERAPI_CONSUL_CONFIGKEY=config/hasherapi
    depends_on:
      - consul
      - hasher
      - redis
      - graylog
    ports:
      - "8088:8088"

  redis:
    container_name: redis
    image: redis:4.0-alpine
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
      - '--requirepass ${REDIS_PASS:-123456789}'
    ports:
      - "6379:6379"

  hasher:
    container_name: hasher
    build:
      context: ../
      dockerfile: build/hasher/Dockerfile
    environment:
      - HASHER_CONSUL_HOST=consul:8500
      - HASHER_CONSUL_CONFIGKEY=config/hasher
    depends_on:
      - graylog
      - consul
    ports:
      - "8090:8090"

  graylog:
    container_name: graylog
    image: graylog/graylog:3.3
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000

  mongo:
    container_name: mongo
    image: mongo:3
  
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g

  consul:
    image: consul:1.10.3
    ports:
      - "8500:8500"
