// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package hasherproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HasherServiceClient is the client API for HasherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HasherServiceClient interface {
	CalculateSha3Hashes(ctx context.Context, in *Inputs, opts ...grpc.CallOption) (*Sha3Hashes, error)
}

type hasherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHasherServiceClient(cc grpc.ClientConnInterface) HasherServiceClient {
	return &hasherServiceClient{cc}
}

func (c *hasherServiceClient) CalculateSha3Hashes(ctx context.Context, in *Inputs, opts ...grpc.CallOption) (*Sha3Hashes, error) {
	out := new(Sha3Hashes)
	err := c.cc.Invoke(ctx, "/HasherService/CalculateSha3Hashes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HasherServiceServer is the server API for HasherService service.
// All implementations must embed UnimplementedHasherServiceServer
// for forward compatibility
type HasherServiceServer interface {
	CalculateSha3Hashes(context.Context, *Inputs) (*Sha3Hashes, error)
	mustEmbedUnimplementedHasherServiceServer()
}

// UnimplementedHasherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHasherServiceServer struct {
}

func (UnimplementedHasherServiceServer) CalculateSha3Hashes(context.Context, *Inputs) (*Sha3Hashes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateSha3Hashes not implemented")
}
func (UnimplementedHasherServiceServer) mustEmbedUnimplementedHasherServiceServer() {}

// UnsafeHasherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HasherServiceServer will
// result in compilation errors.
type UnsafeHasherServiceServer interface {
	mustEmbedUnimplementedHasherServiceServer()
}

func RegisterHasherServiceServer(s grpc.ServiceRegistrar, srv HasherServiceServer) {
	s.RegisterService(&HasherService_ServiceDesc, srv)
}

func _HasherService_CalculateSha3Hashes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Inputs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServiceServer).CalculateSha3Hashes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HasherService/CalculateSha3Hashes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServiceServer).CalculateSha3Hashes(ctx, req.(*Inputs))
	}
	return interceptor(ctx, in, info, handler)
}

// HasherService_ServiceDesc is the grpc.ServiceDesc for HasherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HasherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HasherService",
	HandlerType: (*HasherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateSha3Hashes",
			Handler:    _HasherService_CalculateSha3Hashes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/hasher.proto",
}
