// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: api/hasher.proto

package hasherproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Inputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inputs []string `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
}

func (x *Inputs) Reset() {
	*x = Inputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hasher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Inputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inputs) ProtoMessage() {}

func (x *Inputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_hasher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inputs.ProtoReflect.Descriptor instead.
func (*Inputs) Descriptor() ([]byte, []int) {
	return file_api_hasher_proto_rawDescGZIP(), []int{0}
}

func (x *Inputs) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type Sha3Hashes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hashes []string `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
}

func (x *Sha3Hashes) Reset() {
	*x = Sha3Hashes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hasher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sha3Hashes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sha3Hashes) ProtoMessage() {}

func (x *Sha3Hashes) ProtoReflect() protoreflect.Message {
	mi := &file_api_hasher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sha3Hashes.ProtoReflect.Descriptor instead.
func (*Sha3Hashes) Descriptor() ([]byte, []int) {
	return file_api_hasher_proto_rawDescGZIP(), []int{1}
}

func (x *Sha3Hashes) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

var File_api_hasher_proto protoreflect.FileDescriptor

var file_api_hasher_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x20, 0x0a, 0x06, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x73, 0x22, 0x24, 0x0a, 0x0a, 0x53, 0x68, 0x61, 0x33, 0x48, 0x61, 0x73, 0x68,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x32, 0x3e, 0x0a, 0x0d, 0x48, 0x61,
	0x73, 0x68, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x13, 0x43,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x68, 0x61, 0x33, 0x48, 0x61, 0x73, 0x68,
	0x65, 0x73, 0x12, 0x07, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x1a, 0x0b, 0x2e, 0x53, 0x68,
	0x61, 0x33, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b,
	0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_hasher_proto_rawDescOnce sync.Once
	file_api_hasher_proto_rawDescData = file_api_hasher_proto_rawDesc
)

func file_api_hasher_proto_rawDescGZIP() []byte {
	file_api_hasher_proto_rawDescOnce.Do(func() {
		file_api_hasher_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_hasher_proto_rawDescData)
	})
	return file_api_hasher_proto_rawDescData
}

var file_api_hasher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_hasher_proto_goTypes = []interface{}{
	(*Inputs)(nil),     // 0: Inputs
	(*Sha3Hashes)(nil), // 1: Sha3Hashes
}
var file_api_hasher_proto_depIdxs = []int32{
	0, // 0: HasherService.CalculateSha3Hashes:input_type -> Inputs
	1, // 1: HasherService.CalculateSha3Hashes:output_type -> Sha3Hashes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_hasher_proto_init() }
func file_api_hasher_proto_init() {
	if File_api_hasher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_hasher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Inputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hasher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sha3Hashes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_hasher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_hasher_proto_goTypes,
		DependencyIndexes: file_api_hasher_proto_depIdxs,
		MessageInfos:      file_api_hasher_proto_msgTypes,
	}.Build()
	File_api_hasher_proto = out.File
	file_api_hasher_proto_rawDesc = nil
	file_api_hasher_proto_goTypes = nil
	file_api_hasher_proto_depIdxs = nil
}
