// Code generated by go-swagger; DO NOT EDIT.
// Auto configures api handlers Implementations.

package restapi

import (
	"crypto/tls"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"hasherapi/system/restapi/handler"
	"hasherapi/system/restapi/operations"
)

//go:generate swagger generate server --target ../../../hasherapi --name Hasherapi --spec ../../../api/rest-api.yml --model-package system/restapi/models --server-package system/restapi --implementation-package hasherapi/system/restapi/handler --principal interface{}

// This file auto configures the api backend implementation.
// handler package must already exist.
// handler.New() is implemented by user, and must return an object
// or interface that implements Handler interface defined below.
var Impl Handler = handler.New()

// Handler handles all api server backend configurations and requests
type Handler interface {
	Configurable
	OperationsHandler
}

// Configurable handles all server configurations
type Configurable interface {
	ConfigureFlags(api *operations.HasherapiAPI)
	ConfigureTLS(tlsConfig *tls.Config)
	ConfigureServer(s *http.Server, scheme, addr string)
	CustomConfigure(api *operations.HasherapiAPI)
	SetupMiddlewares(handler http.Handler) http.Handler
	SetupGlobalMiddleware(handler http.Handler) http.Handler
}

/* OperationsHandler  */
type OperationsHandler interface {
	/* GetCheck Получает по id хэш из хранилища (если есть) */
	GetCheck(params operations.GetCheckParams) middleware.Responder
	/* PostSend Получает на вход список строк, хэши от которых нужно посчитать и сохранить */
	PostSend(params operations.PostSendParams) middleware.Responder
}

func configureFlags(api *operations.HasherapiAPI) {
	Impl.ConfigureFlags(api)
}

func configureAPI(api *operations.HasherapiAPI) http.Handler {

	api.ServeError = errors.ServeError

	api.UseSwaggerUI()

	api.JSONConsumer = runtime.JSONConsumer()

	api.JSONProducer = runtime.JSONProducer()

	api.GetCheckHandler = operations.GetCheckHandlerFunc(func(params operations.GetCheckParams) middleware.Responder {
		return Impl.GetCheck(params)
	})
	api.PostSendHandler = operations.PostSendHandlerFunc(func(params operations.PostSendParams) middleware.Responder {
		return Impl.PostSend(params)
	})

	api.PreServerShutdown = func() {}

	api.ServerShutdown = func() {}

	// CustomConfigure can override or add to configurations set above
	Impl.CustomConfigure(api)

	return setupGlobalMiddleware(api.Serve(setupMiddlewares))
}

// The TLS configuration before HTTPS server starts.
func configureTLS(tlsConfig *tls.Config) {
	// Make all necessary changes to the TLS configuration here.
	Impl.ConfigureTLS(tlsConfig)
}

// As soon as server is initialized but not run yet, this function will be called.
// If you need to modify a config, store server instance to stop it individually later, this is the place.
// This function can be called multiple times, depending on the number of serving schemes.
// scheme value will be set accordingly: "http", "https" or "unix".
func configureServer(s *http.Server, scheme, addr string) {
	Impl.ConfigureServer(s, scheme, addr)
}

// The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
// The middleware executes after routing but before authentication, binding and validation.
func setupMiddlewares(handler http.Handler) http.Handler {
	return Impl.SetupMiddlewares(handler)
}

// The middleware configuration happens before anything, this middleware also applies to serving the swagger.json document.
// So this is a good place to plug in a panic handling middleware, logging and metrics.
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return Impl.SetupGlobalMiddleware(handler)
}
